routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NoteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('frontend');

Auth::routes();
Route::get('/show/{slug}', [App\Http\Controllers\HomeController::class, 'show'])->name('show');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::prefix('dashboard')->middleware(['auth', 'web'])->group(function () {
    Route::resource('notes', NoteController::class)->except(['show','destroy']);
    Route::get('notes/{slug}', '\App\Http\Controllers\NoteController@show')->name('notes.show');
    Route::get('notes/delete/{id}', '\App\Http\Controllers\NoteController@destroy')->name('note.destroy');
});

app/Models/Note.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * App\Models\Note
 *
 * @method static \Illuminate\Database\Eloquent\Builder|Note newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Note newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Note query()
 * @mixin \Eloquent
 * @property int $id
 * @property string $note_title
 * @property string $slug
 * @property string|null $description
 * @property string|null $image
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @method static \Illuminate\Database\Query\Builder|Note onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|Note whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Note whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Note whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Note whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Note whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Note whereNoteTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Note whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Note whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|Note withTrashed()
 * @method static \Illuminate\Database\Query\Builder|Note withoutTrashed()
 * @property int $user_id
 * @method static \Illuminate\Database\Eloquent\Builder|Note whereUserId($value)
 */
class Note extends Model
{
    use HasFactory,SoftDeletes;
    protected $fillable = ['note_title','description'];
}

app/Http/Controllers/API/Note/NoteApiController.php
<?php

namespace App\Http\Controllers\API\Note;

use App\Http\Controllers\Controller;
use App\Http\Requests\NoteRequest;
use App\Http\Resources\NoteOneResource;
use App\Http\Resources\NoteResource;
use App\Layers\BusinessLayer\notes\NoteLayer;
use App\Models\Note;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NoteApiController extends Controller
{
    private $accessLayer;
    public function __construct(NoteLayer $accessLayer)
    {
        $this->accessLayer = $accessLayer;
    }

    public function index()
    {
        if (Auth::user()){
            $model = Note::get();
        }
        if ($model)
            return response([
                'status' => 'success',
                'data' => NoteResource::collection($model),
            ], 200);
        return response([
            'status' => 'success',
            'data' => null,
        ], 200);

    }

    public function store(NoteRequest $request)
    {
        $model = $this->accessLayer->store(
            $request->input('note_title'),
            $request->input('description'),
            $request
        );
        return response([
            'status' => 'success',
            'data'=>  new NoteOneResource($model),
        ]);
    }

    public function show($slug)
    {
        $item = Note::where('slug',$slug)->firstOrFail();
        return response([
            'status' => 'success',
            'data'=>  new NoteOneResource($item),
        ]);
    }

    public function edit($id)
    {
        $item = Note::find($id);
        return response([
            'status' => 'success',
            'data'=>  new NoteOneResource($item),
        ]);
    }

    public function update(NoteRequest $request , $id)
    {
        $models = Note::findOrFail($id);

        $item = $this->accessLayer->update(
            $models,
            $request->input('note_title'),
            $request->input('description'),
            $request
        );
        return response([
            'status' => 'success',
            'data'=>  new NoteOneResource($item),
        ]);
    }

    public function destroy($id)
    {
        $model = Note::find($id);
        if ($model->delete())
        {
            return response([
                'status' => 'success',
                'message'=>  'have been delete',
        ]);
        }else{
            return response([
                'status' => 'failed',
                'message'=>  'error',
            ]);
        }
    }
}

app/Http/Controllers/NoteController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\NoteRequest;
use App\Layers\BusinessLayer\notes\NoteLayer;
use App\Models\Note;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class NoteController extends Controller
{
    protected $accessLayer;
    public function __construct(NoteLayer $accessLayer)
    {
        $this->accessLayer = $accessLayer;
    }

    public function joinTest()
    {
        if (Auth::user()) {
            //$model = Note::get();
            $model = DB::table('notes')
                ->join('users','users.id',"=",'notes.user_id')
                ->get();
        }
        dd( $model);
        //return view('notes.index', compact('model'));

    }

    public function index()
    {
        if (Auth::user()) {
            $model = Note::get();
        }
        return view('notes.index', compact('model'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('notes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(NoteRequest $request)
    {
        //$this->validate($request, $this->accessLayer->getValidationRules());

        $model = $this->accessLayer->store(
            $request->input('note_title'),
            $request->input('description'),
            $request
        );
        return redirect()->route('notes.show', $model->slug);

    }


    public function show($slug)
    {
        if (Auth::user()) {
            $item = Note::where('slug', $slug)->firstOrFail();
            return view('notes.show', compact('item'));
        } else
            redirect()->back();

    }

    public function showBuSlug($slug)
    {
        $item = Note::where('slug', $slug)->firstOrFail();
        return view('notes.show', compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Note $note
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Note::find($id);
        return view('notes.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Note $note
     * @return \Illuminate\Http\Response
     */
    public function update(NoteRequest $request, $id)
    {
        $models = Note::findOrFail($id);
        $this->validate($request, $this->accessLayer->getValidationRules());

        $this->accessLayer->update(
            $models,
            $request->input('note_title'),
            $request->input('description'),
            $request
        );
        return redirect()->route('notes.show', $models->slug);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Note $note
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $model = Note::find($id);
        $model->delete();

        return redirect()->route('notes.index');
    }
}

resources/views/notes/create.blade.php
@extends('layouts.app')

@section('content')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("home")}}">{{__('model.breadcrumb.home')}}</a></li>
            <li class="breadcrumb-item"><a href="{{route('notes.index')}}">{{__('modules/note.notesAtt.name')}}</a></li>
        </ol>
    </nav>

    <div class="height-100 bg-light">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card-body">
                    @if(session()->has('error'))
                        <div class="alert alert-danger" style="padding: 20px;">
                            <p>
                                {{session()->get('error')}}
                            </p>
                        </div>
                    @endif
                    @if ($errors->any())
                        <div class="alert alert-danger" style="padding: 20px;">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                <form  method="POST" action="{{ route('notes.store') }}" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="note_title">
                            @lang('modules/note.attr.note_title')</label>
                        <input id="note_title" type="text" class="form-control" name="note_title"
                               value="{{ old('note_title') }}"
                               data-v-p="string[required|range:4,190]" autofocus>
                        <div class="invalid-feedback"></div>
                    </div>

{{--
                        <div class="form-group">
                            <label for="slug">Link</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">{{env('APP_URL') . '/notes/'}}</span>
                                </div>
                                <input type="text" class="form-control"
                                       id="slug" name="slug" value="{{ old('slug') }}" readonly>
                            </div>
                        </div>
--}}

                    <div class="form-group">
                        <label for="description">
                            @lang('modules/note.attr.description')</label>
                        <input id="description" type="text" class="form-control" name="description"
                               value="{{ old('description') }}"
                               data-v-p="string[required|range:4,190]" autofocus>
                        <div class="invalid-feedback"></div>
                    </div>

                    <div class="form-group">
                        <label for="image">
                            @lang('modules/note.attr.image')</label>
                        <input id="image" type="file" class="form-control" name="image"
                               value="{{ old('image') }}"
                               data-v-p="string[required|range:4,190]" autofocus>
                        <div class="invalid-feedback"></div>
                    </div>

                    <button class="btn btn-success" id="spa-submit">
                        @lang('general.btn.save')
                    </button>
                </form>
            </div>
        </div>

    </div>

@endsection

resources/views/notes/edit.blade.php
@extends('layouts.app')

@section('content')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("home")}}">{{__('model.breadcrumb.home')}}</a></li>
            <li class="breadcrumb-item"><a href="{{route('notes.index')}}">{{__('modules/note.notesAtt.name')}}</a></li>
        </ol>
    </nav>

    <div class="height-100 bg-light">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card-body">
                    @if(session()->has('error'))
                        <div class="alert alert-danger" style="padding: 20px;">
                            <p>
                                {{session()->get('error')}}
                            </p>
                        </div>
                    @endif
                    @if ($errors->any())
                        <div class="alert alert-danger" style="padding: 20px;">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                <form  method="POST" action="{{ route('notes.update',$item->id) }}" enctype="multipart/form-data" novalidate>
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="note_title">
                            @lang('modules/note.attr.note_title')</label>
                        <input id="note_title" type="text" class="form-control" name="note_title"
                               value="{{ old('note_title',$item->note_title) }}"
                               data-v-p="string[required|range:4,190]" autofocus>
                        <div class="invalid-feedback"></div>
                    </div>

{{--
                        <div class="form-group">
                            <label for="slug">Link</label>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">{{env('APP_URL') . '/notes/'}}</span>
                                </div>
                                <input type="text" class="form-control"
                                       id="slug" name="slug" value="{{ old('slug') }}" readonly>
                            </div>
                        </div>
--}}

                    <div class="form-group">
                        <label for="description">
                            @lang('modules/note.attr.description')</label>
                        <input id="description" type="text" class="form-control" name="description"
                               value="{{ old('description',$item->description) }}"
                               data-v-p="string[required|range:4,190]" autofocus>
                        <div class="invalid-feedback"></div>
                    </div>

                    <div class="form-group">
                        <label for="image">
                            @lang('modules/note.attr.image')</label>
                        <input id="image" type="file" class="form-control" name="image"
                               value="{{ old('image') }}"
                               data-v-p="string[required|range:4,190]" autofocus>
                        <div class="invalid-feedback"></div>
                    </div>

                    <button class="btn btn-success" id="spa-submit">
                        @lang('general.btn.save')
                    </button>
                </form>
            </div>
        </div>

    </div>

@endsection

resources/views/notes/index.blade.php
@extends('layouts.app')

@section('content')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("home")}}">{{__('model.breadcrumb.home')}}</a></li>
            <li class="breadcrumb-item"><a href="{{route('notes.index')}}">{{__('modules/note.notesAtt.name')}}</a></li>
        </ol>
    </nav>
    <section class="pt-7 pt-md-1">
    <div class="container bg-light">
        <div class="form-group">
            <a href="{{route('notes.create')}}" class="btn btn-primary">@lang('modules/note.notesAtt.create.title')</a>

        </div>


        @foreach($model as $item)
            <div class="row">
                <div class="col-12">
                    <div class="card" style="width: 18rem;">
                        <img src="{{asset('images/notes/'.$item->image)}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{$item->note_title}}</h5>
                            <p class="card-text">{{$item->description}}</p>
                            <a href="{{route('notes.show',$item->slug)}}" class="btn btn-primary">Show</a>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach

    </div>

    </section>


@endsection

resources/views/notes/show.blade.php
@extends('layouts.app')

@section('content')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("home")}}">{{__('model.breadcrumb.home')}}</a></li>
            <li class="breadcrumb-item"><a href="{{route('notes.index')}}">{{__('modules/note.notesAtt.name')}}</a></li>
        </ol>
    </nav>
    <section class="pt-7 pt-md-1">
    <div class="container bg-light">
        <div class="form-group">
            <a href="{{route('notes.edit',$item->id)}}" class="btn btn-warning">@lang('modules/note.notesAtt.edit.title')</a>
            <a href="{{route('note.destroy',$item->id)}}" class="btn btn-danger">@lang('modules/note.notesAtt.delete.title')</a>
            <a href="{{route('show',$item->slug)}}" class="btn btn-primary">@lang('modules/note.notesAtt.show.title')</a>

        </div>



            <div class="row">
                <div class="col-12">
                    <div class="card" style="width: 18rem;">
                        <img src="{{asset('images/notes/'.$item->image)}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{$item->note_title}}</h5>
                            <p class="card-text">{{$item->description}}</p>
                            <a href="{{route('notes.show',$item->slug)}}" class="btn btn-primary">Show</a>
                        </div>
                    </div>
                </div>
            </div>


    </div>

    </section>


@endsection

resources/views/notes/show_out.blade.php
{{--@extends('layouts.app')

@section('content')

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("home")}}">{{__('model.breadcrumb.home')}}</a></li>
            <li class="breadcrumb-item"><a href="{{route('notes.index')}}">{{__('modules/note.notesAtt.name')}}</a></li>
        </ol>
    </nav>--}}
    <section class="pt-7 pt-md-1">
    <div class="container bg-light">
{{--        <div class="form-group">
            <a href="{{route('notes.edit',$item->id)}}" class="btn btn-warning">@lang('modules/note.notesAtt.edit.title')</a>
            <a href="{{route('notes.destroy',$item->id)}}" class="btn btn-danger">@lang('modules/note.notesAtt.delete.title')</a>

        </div>--}}



            <div class="row">
                <div class="col-12">
                    <div class="card" style="width: 18rem;">
                        <img src="{{asset('images/notes/'.$item->image)}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">{{$item->note_title}}</h5>
                            <p class="card-text">{{$item->description}}</p>
                            <a href="{{route('notes.show',$item->slug)}}" class="btn btn-primary">Show</a>
                        </div>
                    </div>
                </div>
            </div>


    </div>

    </section>

{{--
@endsection--}}