routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\NoteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('frontend');

Auth::routes();
Route::get('/show/{slug}', [App\Http\Controllers\HomeController::class, 'show'])->name('show');

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::prefix('dashboard')->middleware(['auth', 'web'])->group(function () {
    Route::resource('notes', NoteController::class)->except(['show','destroy']);
    Route::get('notes/{slug}', '\App\Http\Controllers\NoteController@show')->name('notes.show');
    Route::get('notes/delete/{id}', '\App\Http\Controllers\NoteController@destroy')->name('note.destroy');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('/js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" >
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css" >

    <!-- Styles -->
    <link href="{{ asset('/css/app.css') }}" rel="stylesheet">
</head>
<body>
    @if(Auth::user())
    @include('layouts.sidebar')
    @endif


    <div id="app">
        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

<script>
    document.addEventListener("DOMContentLoaded", function(event) {

        const showNavbar = (toggleId, navId, bodyId, headerId) =>{
            const toggle = document.getElementById(toggleId),
                nav = document.getElementById(navId),
                bodypd = document.getElementById(bodyId),
                headerpd = document.getElementById(headerId)

// Validate that all variables exist
            if(toggle && nav && bodypd && headerpd){
                toggle.addEventListener('click', ()=>{
// show navbar
                    nav.classList.toggle('show')
// change icon
                    toggle.classList.toggle('bx-x')
// add padding to body
                    bodypd.classList.toggle('body-pd')
// add padding to header
                    headerpd.classList.toggle('body-pd')
                })
            }
        }

        showNavbar('header-toggle','nav-bar','body-pd','header')

        /*===== LINK ACTIVE =====*/
        const linkColor = document.querySelectorAll('.nav_link')

        function colorLink(){
            if(linkColor){
                linkColor.forEach(l=> l.classList.remove('active'))
                this.classList.add('active')
            }
        }
        linkColor.forEach(l=> l.addEventListener('click', colorLink))

// Your code to run since DOM is loaded and ready
    });

</script>
</html>

resources/views/layouts/nav.blade.php
<div class="bg-gray-50 h-16 w-full">
    <nav class="flex items-center justify-between px-64 mx-auto py-2">
        <img class="h-12" src="{{asset('images/src/logo.png')}}" alt="">
        <div>
            <ul>
                <li>
                    <a href="" class="nav-a" >
                        Home
                    </a>
                    <a href="" class="nav-a">
                        Services
                    </a>
                    <a href="" class="nav-a">
                        Clients
                    </a>
                    <a href="" class="nav-a">
                        News
                    </a>
                    <a href="" class="nav-a">
                        Contact
                    </a>
                </li>
            </ul>
        </div>
        <div>
            <button class="btn-nav">
                Sign Up
            </button>
            <button class="btn-nav">
                Log in
            </button>
        </div>

    </nav>
</div>

resources/views/layouts/sidebar.blade.php
<body id="body-pd">
<header class="header" id="header">
    <div class="header_toggle"> <i class='bx bx-menu' id="header-toggle"></i> </div>
</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div>
            <a href="{{route("frontend")}}" class="nav_logo">
                <i class='bx bx-layer nav_logo-icon'>

                </i>
                <span class="nav_logo-name">
                   {{__('model.side_bar.apptech')}}
                </span>
            </a>
            <div class="nav_list">
                <a href="{{route("home")}}" class="nav_link active">
                    <i class='bx bx-grid-alt nav_icon'>
                    </i>
                    <span class="nav_name">
                        {{__('model.side_bar.dashboard')}}
                    </span>
                </a>
              {{--  <a href="#" class="nav_link">
                    <i class='bx bx-user nav_icon'>

                    </i>
                    <span class="nav_name">
                        Users
                    </span>
                </a>
                <a href="#"
                   class="nav_link">
                    <i class='bx bx-message-square-detail nav_icon'>

                    </i> <span class="nav_name">
                        Messages
                    </span>
                </a>--}}
                <a href="{{route('notes.index')}}" class="nav_link">
                    <i class='bx bx-bookmark nav_icon'>

                    </i> <span class="nav_name">
                       {{__('model.side_bar.notes')}}
                    </span>
                </a>
                <a href="#" class="nav_link">
                    <i class='bx bx-folder nav_icon'>

                    </i> <span class="nav_name">
                        Files
                    </span>
                </a>
                <a href="#" class="nav_link">
                    <i class='bx bx-bar-chart-alt-2 nav_icon'>

                    </i>
                    <span class="nav_name">
                        Stats
                    </span>

                </a>
            </div>
        </div>
        <a href="{{ route('logout') }}" class="nav_link"
           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
            <i class='bx bx-log-out nav_icon'>

            </i>
            <span class="nav_name">
                {{ __('Logout') }}
            </span>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                @csrf
            </form>
        </a>
    </nav>
</div>